### ISSUE TITLE
Broken FastText Social Network Model download

### ISSUE THREAD

**Issue by MilkyCode13** [bureaucratic-labs/dostoevsky#67] opened 2020-02-27 15:28 UTC
Cannot download models already for 2 days. Getting error message:
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.1/x64/bin/dostoevsky", line 22, in <module>
    downloader.download(source=source, destination=destination)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/dostoevsky/data/__init__.py", line 40, in download
    tar.extractall(os.path.dirname(destination_path))
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/tarfile.py", line 2026, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/tarfile.py", line 2067, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/tarfile.py", line 2139, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/tarfile.py", line 2188, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by dveselov** [comment] 2020-02-28 08:06
Hi, I can't reproduce this error. Please, check your internet connection.

**Comment by dveselov** [comment] 2020-02-28 08:08
Not closing for now, if someone has a similar problem, please write a message here.

**Comment by Archelunch** [comment] 2020-03-27 13:16
Can't download weights
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>`

**Comment by Archelunch** [comment] 2020-03-27 13:22
> Can't download model
> `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>`

Solved this problem `conda install -c conda-forge certifi `

**Closed** 2020-10-06 07:21 UTC
Labels: bug
